config/routes.rb
Rails.application.routes.draw do
  resources :velos
  get 'map/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/velo.rb
class Velo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/map_controller.rb
require 'net/http'
class MapController < ApplicationController
  def index

    uri = URI("https://api.citybik.es/v2/networks")
    response = Net::HTTP.get_response(uri)



    p"****************************************************************************************"

    data = JSON.parse(response.body)
    @arraypoint = []
    @arrayinfo = []
    p data["networks"][1]
    for item in data["networks"]
      tempopoint = [item["location"]["latitude"], item["location"]["longitude"]]
      tempoinfo =  [item["name"], item["location"]["city"], item["location"]["country"]]
      @arraypoint.push(tempopoint)
      @arrayinfo.push(tempoinfo)
    end
    p "****************************************************************************************"
    for key, value in data["networks"][1]
      p "#{key} => #{value}"
      if key == "location"
        p data["networks"][1]["location"]["latitude"]
        p data["networks"][1]["location"]["longitude"]
      end
    end
    @arraycenter = [data["networks"][1]["location"]["latitude"], data["networks"][1]["location"]["longitude"]]
    p "-----------------------------------------"

    @arraypointbdd = []
    @arrayinfobdd = []

      veloLong = Velo.select(:longitude).map(&:longitude)
      veloLat = Velo.select(:latitude).map(&:latitude)
      name = Velo.select(:name).map(&:name)
      city = Velo.select(:city).map(&:city)
      country = Velo.select(:country).map(&:country)
      company = Velo.select(:company).map(&:company)
      veloCoord = veloLat, veloLong
      veloInfo = name, city, country, company
      @arraypointbdd.push(veloCoord)
      @arrayinfobdd.push(veloInfo)

      p veloLong[1]
      p veloLat[1]






  end



end

app/controllers/velos_controller.rb
require 'net/http'
class VelosController < ApplicationController
  before_action :set_velo, only: %i[ show edit update destroy ]

  # GET /velos or /velos.json
  def index
    @velos = Velo.all

  end

  # GET /velos/1 or /velos/1.json
  def show
  end

  # GET /velos/new
  def new
    @velo = Velo.new
  end

  # GET /velos/1/edit
  def edit
  end

  # POST /velos or /velos.json
  def create
    @velo = Velo.new(velo_params)

    respond_to do |format|
      if @velo.save
        format.html { redirect_to velo_url(@velo), notice: "Le vélo a été ajouté avec succès." }
        format.json { render :show, status: :created, location: @velo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @velo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /velos/1 or /velos/1.json
  def update
    respond_to do |format|
      if @velo.update(velo_params)
        format.html { redirect_to velo_url(@velo), notice: "Le vélo a été modifié avec succès." }
        format.json { render :show, status: :ok, location: @velo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @velo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /velos/1 or /velos/1.json
  def destroy
    @velo.destroy

    respond_to do |format|
      format.html { redirect_to velos_url, notice: "Le vélo a été supprimé avec succès." }
      format.json { head :no_content }
    end
  end

  public
    # Use callbacks to share common setup or constraints between actions.
    def set_velo
      @velo = Velo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def velo_params
      params.require(:velo).permit(:name, :company, :city, :country, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/velos_helper.rb
module VelosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeafletRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/footer.html.erb
</body>
</html>

app/views/layouts/header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaflet debug page</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin="" />
  <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js" integrity="sha512-WXoSHqw/t26DszhdMhOXOkI7qCiv5QWXhH9R7CgvgZMHz1ImlkVQ3uNsiQKu5wwbbxtPzFXd1hK4tzno2VqhpA==" crossorigin=""></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--  Bootstrap-->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</head>
<body>

<!--barre de menu-->
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Word by Bike</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/velos">Les loueurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/map/index">Maps</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/map/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaflet debug page</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin="" />
  <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js" integrity="sha512-WXoSHqw/t26DszhdMhOXOkI7qCiv5QWXhH9R7CgvgZMHz1ImlkVQ3uNsiQKu5wwbbxtPzFXd1hK4tzno2VqhpA==" crossorigin=""></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--  Bootstrap-->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</head>
<body>

<!--barre de menu-->
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">World by Bike</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/velos">Les loueurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/map/index">Maps</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- fin -- barre de menu-->

<h1 class="titre">La Maps des vélos </h1>



<!--Emplacement de la map-->
<div id="map" class=" centered-element"></div>

<script type="text/javascript">

    // Position sur la map au chargement
    map = L.map('map').setView(<%= @arraycenter %>, 13)

    // chargement et affichage des couches de tuiles sur la carte
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
        maxZoom: 3
    }).addTo(map)

    // Markers de l'api
    var tabpoint = <%= @arraypoint %>// Coordonnées
    var tabinfo = <%=raw  @arrayinfo %>// Informations
        console.log(tabinfo);

    for (var i = 0; i < tabpoint.length; i++) {
        //Insertion des markers dans la map
        var marker = L.marker(tabpoint[i]).addTo(map);
        //console.log(marker);
        //Ajout de l'info bulle au marker
        marker.bindPopup(tabpoint[i][0] + '<br>' + tabpoint[i][1] + "<br>" + tabinfo[i][0] + "<br>" + tabinfo[i][1] + "<br>" + tabinfo[i][2])
    }

    // Aspect des markers issus de la bdd
    var greenIcon = new L.Icon({
        iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-green.png',
        shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
        iconSize: [25, 41],
        iconAnchor: [12, 41],
        popupAnchor: [1, -34],
        shadowSize: [41, 41]
    });

    // Markers de la bdd
    var tabpointbdd = <%= @arraypointbdd %> // Coordonnées
    var tabinfobdd = <%=raw  @arrayinfobdd %> // Informations
    var tabtaille = tabpointbdd[0][0].length;
    //console.log(tabtaille);
    for (var i = 0; i < tabtaille; i++) {

        var point = [tabpointbdd[0][0][i] , tabpointbdd[0][1][i]];
        //console.log("tableau point " + point);

        //Insertion des markers dans la map
        var marker2 = L.marker(point ,{icon: greenIcon}).addTo(map);
        //console.log(marker2);

        //Ajout de l'info bulle au marker
         marker2.bindPopup(tabpointbdd[0][0][i] + '<br>' + tabpointbdd[0][1][i] + "<br>"+ "<br>" + tabinfobdd[0][0][i] + "<br>" + tabinfobdd[0][1][i] + "<br>" + tabinfobdd[0][2][i] )

    }


</script>

</body>
</html>

app/views/velos/_form.html.erb
<%= form_with(model: velo) do |form| %>
  <% if velo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(velo.errors.count, "error") %> prohibited this velo from being saved:</h2>

      <ul>
        <% velo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/velos/_velo.html.erb
<div id="<%= dom_id velo %>">
  <p>
    <strong>Name:</strong>
    <%= velo.name %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= velo.company %>
  </p>

  <p>
    <strong>City:</strong>
    <%= velo.city %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= velo.country %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= velo.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= velo.longitude %>
  </p>

</div>

app/views/velos/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaflet debug page</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin="" />
  <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js" integrity="sha512-WXoSHqw/t26DszhdMhOXOkI7qCiv5QWXhH9R7CgvgZMHz1ImlkVQ3uNsiQKu5wwbbxtPzFXd1hK4tzno2VqhpA==" crossorigin=""></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--  Bootstrap-->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</head>
<body>

<!--barre de menu-->
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">World by Bike</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/velos">Les loueurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/map/index">Maps</a>
        </li>
      </ul>
    </div>
  </div>
</nav>





<h1 class="titre">Edition de <%=  @velo.name %></h1>

<button type="button" class="btn btn-secondary btnOption "><%= link_to "Retour à la liste des vélos", velos_path %></button>
<button type="button" class="btn btn-primary btnOption btnEdit"><%= link_to "Voir les détails", @velo %></button>



<!--Form-->
<div class="container " id="details">
  <div class="row">
    <div class="text-center h-100 d-flex align-items-center justify-content-center">
      <div class="card col-lg-7 col-md-8 col-sm-8" >
        <div class="card-body">

<%= render "form", velo: @velo %>

        </div>
      </div>
    </div>
  </div>
</div>





</body>
</html>

app/views/velos/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaflet debug page</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin="" />
  <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js" integrity="sha512-WXoSHqw/t26DszhdMhOXOkI7qCiv5QWXhH9R7CgvgZMHz1ImlkVQ3uNsiQKu5wwbbxtPzFXd1hK4tzno2VqhpA==" crossorigin=""></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--  Bootstrap-->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</head>
<body>

<!--barre de menu-->
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">World by Bike</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/velos">Les loueurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/map/index">Maps</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p style="color: green"><%= notice %></p>

<h1 class="titre">Listes des loueurs de vélos</h1>

<button type="button" class="btn btn-info btnOption" > <%= link_to "Ajouter un vélo +", new_velo_path %> </button>

<!--Liste des loueurs de vélos -->
<div id="velosList">
  <div class="row">
    <% @velos.each do |velo| %>
      <%#= render velo %>
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%=  velo.name %></h5>
              <p class="card-text"><%=  velo.company %></p>
              <p class="card-text"><%=  velo.country %> , <%= velo.city %></p>
              <button type="button" class="btn btn-primary"><%= link_to "Voir les détails", velo %></button>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

</body>
</html>

app/views/velos/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaflet debug page</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin="" />
  <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js" integrity="sha512-WXoSHqw/t26DszhdMhOXOkI7qCiv5QWXhH9R7CgvgZMHz1ImlkVQ3uNsiQKu5wwbbxtPzFXd1hK4tzno2VqhpA==" crossorigin=""></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--  Bootstrap-->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</head>
<body>

<!--barre de menu-->
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Word by Bike</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/velos">Les loueurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/map/index">Maps</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<h1 class="titre">Ajouter un nouveau loueur</h1>

<button type="button" class="btn btn-secondary btnOption"><%= link_to "Retour à la liste des vélos", velos_path %></button>

<!--Form-->
<div class="container " id="details">
  <div class="row">
    <div class="text-center h-100 d-flex align-items-center justify-content-center">
      <div class="card col-lg-7 col-md-8 col-sm-8" >
        <div class="card-body">

          <%= render "form", velo: @velo %>

        </div>
      </div>
    </div>
  </div>
</div>



</body>
</html>

app/views/velos/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaflet debug page</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin="" />
  <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js" integrity="sha512-WXoSHqw/t26DszhdMhOXOkI7qCiv5QWXhH9R7CgvgZMHz1ImlkVQ3uNsiQKu5wwbbxtPzFXd1hK4tzno2VqhpA==" crossorigin=""></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--  Bootstrap-->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</head>
<body>

<!--barre de menu-->
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">World by Bike</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/velos">Les loueurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/map/index">Maps</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<h1 class="titre"><%=  @velo.name %></h5></h1>

<button type="button" class="btn btn-secondary btnOption"><%= link_to "Retour à la liste des vélos", velos_path %></button>

<div class="container " id="details">
  <div class="row">
    <div class="text-center h-100 d-flex align-items-center justify-content-center">
      <div class="card col-lg-7 col-md-8 col-sm-8" >
        <div class="card-body">
          <%= render @velo %>

            <button type="button" class="btn btn-warning"><%= link_to "Editer ce vélo", edit_velo_path(@velo) %> </button>
            <button type="button" class="btn btn-danger"><%= link_to "Supprimer ce vélo", @velo, method: :delete %></button>

        </div>
      </div>

  <%#= button_to "Supprimer", @velo, method: :delete %>

    </div>
  </div>
</div>

</body>
</html>